###
GET http://localhost:3000/api/cliente

###
GET http://localhost:3000/api/cliente/2

###
POST http://localhost:3000/api/cliente
Content-Type: application/json

{
     "nombre": "elena",
  "apellidos": "jimenez",
  "direccion": "paseo san juan 23",
  "telefono": 783672892,
  "fecha_nacimiento": "1983-01-22",
  "email": "helena@gmail.com",
  "dni": "17283902J"
}

###
DELETE http://localhost:3000/api/cliente/5

###
PUT http://localhost:3000/api/cliente/2
Content-Type: application/json

{
  "nombre": "elena",
  "apellidos": "jimenez",
  "direccion": "paseo san juan 23",
  "telefono": 783672892,
  "fecha_nacimiento": "1983-01-22T23:00:00.000Z",
  "email": "helena@gmail.com",
  "dni": "17283902J"
}







###
GET http://localhost:3000/api/hotel

###
GET http://localhost:3000/api/hotel/1


###
POST http://localhost:3000/api/hotel
Content-Type: application/json

{
    "nombre": "Palacito",
    "direccion": "c. rio verde 67",
    "ciudad": "Barcelona",
    "numero_estrellas": "4",
    "descripcion": "Hotel bien ubicado en el centro de vigo",
    "tarifa": "60.00"
}

###
DELETE http://localhost:3000/api/hotel/5

###
PUT http://localhost:3000/api/hotel/2
Content-Type: application/json

{
   "nombre": "Palace",
    "direccion": "c. rio verde 67",
    "ciudad": "vigo",
    "numero_estrellas": "4",
    "descripcion": "Hotel bien ubicado en el centro de vigo",
    "tarifa": "60.00"
}





###
GET http://localhost:3000/api/viaje

###
GET http://localhost:3000/api/viaje/4

###
POST http://localhost:3000/api/viaje
Content-Type: application/json

{
    "fecha_salida": "2025-10-01",
    "fecha_vuelta": "2023-11-01",
    "id_ida": "234754VLG",
    "id_vuelta": "951847IBR",
    "hotel_id": 5,
    "cliente_id": 7
}

###
DELETE http://localhost:3000/api/viaje/5

###
PUT http://localhost:3000/api/viaje/2
Content-Type: application/json

{
    "fecha_salida": "2025-10-01",
    "fecha_vuelta": "2023-11-01",
    "id_ida": "234754VLG",
    "id_vuelta": "951847IBR",
    "hotel_id": 5,
    "cliente_id": 7
}
