###
GET http://localhost:3000/api/clientes

###
GET http://localhost:3000/api/clientes/2




###
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Luis",
    "apellidos": "garcia",
    "direccion": "libertad 45",
    "telefono": 664436758,
    "fecha_nacimiento": "1990-09-13",
    "email": "paco12345@gmail.com",
    "dni": "28296162M"
}

###
DELETE http://localhost:3000/api/clientes/5

###
PUT http://localhost:3000/api/clientes/2
Content-Type: application/json

{
  "nombre": "elena",
  "apellidos": "jimenez",
  "direccion": "paseo san juan 23",
  "telefono": 783672892,
  "fecha_nacimiento": "1983-01-22T23:00:00.000Z",
  "email": "helena@gmail.com",
  "dni": "17283902J"
}
